[build]
publish = "public"
command = "hugo --baseURL $URL"

[build.environment]
HUGO_VERSION = "0.126.1"
HUGO_THEME = "repo"

[context.deploy-preview]
command = "chugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"
